### ISSUE TITLE
Chrome's screensharing status is incorrect

### ISSUE THREAD

**Issue by ZephyrXero** [webrtcftw/iswebrtcreadyyet.com#22]
Chrome and Chromium both have their "ready" status for screensharing marked as Green...but then, if you mouse over it you see a caveat that it requires an extension. Being that webRTC is all about being able to natively do teleconferencing in your browser without plugins, I think this should make them Yellow, at best.

**Comment by fippo** [comment]
I disagree. Users seem to accept installing these extensions (10kb in size) and the UX for this can be controlled via javascript. 
Which makes the chrome 34+ way a big improvement over the please-go-to-chrome-flags-and-enable-it-restart-your-browser-afterwards.

Besides, we're not going to get "native" screensharing until the security implications have been resolved and I don't see @juberti doing this any faster just because we make this yellow instead of green.

**Comment by fippo** [comment]
Changed back to yellow due to hangouts being whitelisted. If Google doesn't dogfood on the extension way, it obviously isn't ready.
