### ISSUE TITLE
Spelling/grammar fixes

### ISSUE THREAD

**Issue by malakada** [webrtcftw/iswebrtcreadyyet.com#7]
I noticed some spelling/grammar errors, so I pulled the project down and corrected them and tried to submit a PR but access is denied. :)

Changes are:

MediaStream API - When you request user media or get media from a peer it's held in a MediaStream object. Having the ability to add/remove tracks, mute, and apply constraints makes it possible to do audio processing and control bandwidth consumption.

Echo cancellation - This may be the most subjective item in this list. 3 or 4 users should be able to use a service like Talky without headphones on and not experience feedback problems.

And below the graph/table:
See an error? This site is open source on Github, please let us know by

Happy to push the branch if you add me, or you can update yourself. :)

M

**Comment by ike** [comment]
Hi there @melissanoelle! Thanks for taking the time to fix these things... 

Since this is a public repo, you have to fork the project to your own user, make the changes, and then submit a pull request from your fork. I hope that's not too much trouble...

Thanks again! We appreciate anyone's help. :+1:
